name: Java CD

on: 
  release:
    types: published

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to Bintray
      id: deploy-to-bintray
      run: |
        mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
        mvn deploy -s .github/bintray-settings.xml || echo "deploy failed" >&2
      env:
        BINTRAY_USERNAME: ${{ secrets.bintray_username }}
        BINTRAY_PASSWORD: ${{ secrets.bintray_password }}

    - name: Move sources jar file
      run: mv target/*-sources.jar sources.jar

    - name: Move target jar file
      run: mv target/*.jar target.jar

    - name: Attach source jar to release
      id: upload-source-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: sources.jar
        asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}-sources.jar
        asset_content_type: application/zip

    - name: Attach target jar to release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target.jar
        asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.jar
        asset_content_type: application/zip